defaults:
  - model: gpt2
  - generation: debug
  - training: basic
  - _self_

# Training parameters
num_epochs: 4
num_steering_vectors: 10
seed: 1234

context: "System: You are a helpful assistant.\nUser: I keep forgetting to water my plants. Any tips?\nAssistant: Set phone reminders for specific days, or use the \"finger test\" - stick your finger an inch into the soil, and if it's dry, it's time to water. Most houseplants need water every 1-2 weeks.\n"

# Generation parameters
max_new_tokens: 100
do_sample: false


# Hardware
cpu: false