user_messages:
  - "Tell me a story."
  - "Tell me a joke."
  - "Write a poem for me."
  - "Write some song lyrics."
  - "Give me some ideas for some fun weekend activities."
  - "Give me some ideas for a birthday party."
  - "Give me ideas for indoor activities on a rainy day."
  - "Come up with a themed dinner party concept."
  - "Create a motivational quote for someone facing a challenge."
  - "Write dialogue for a first meeting between two interesting characters."
  - "I'm bored... Entertain me!"
  - "What should we talk about today?"
  - "What do you want to talk about?"
  - "Why don't you choose a topic of conversation for us?"
  - "I need some new hobbies. Can you give me some ideas?"
  - "Give me some activity ideas for later today."
  - "Write a short letter from one fictional character to another."
  - "Write a short children's bedtime story."
  - "Create a riddle or brain teaser."
  - "Write a letter from the perspective of a historical figure."
  - "Write a script for a short film."