user_messages:
  - "Tell me a joke"
  - "I'm bored... Entertain me!"
  - "What should we talk about today?"
  - "Write a short letter from one fictional character to another."
  - "Write a short children's bedtime story."
  - "Write a letter from the perspective of a historical figure."